{{define 'service_name' (hyphen service.name) ~}}
{{define 'multi_staged_build'  (not environment.uses_locally_built_container_images) ~}}
{{#if multi_staged_build ~}}
FROM gradle:{{component.gradle_version}}-jdk{{component.jdk_base_version}} AS build
COPY --chown=gradle:gradle . /home/gradle/
WORKDIR /home/gradle
RUN gradle build --no-daemon
{{/if}}

FROM {{component.container_base_image}}
RUN mkdir /app
{{#if multi_staged_build ~}}
COPY --from=build /home/gradle/build/libs/{{service_name}}*.jar /app/api.jar
{{else}}
COPY ./build/libs/{{service_name}}*.jar /app/api.jar
{{/if}}
COPY ./entrypoint.sh /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
